version: '3'
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init_conf.sh:/docker-entrypoint-initdb.d/init_conf.sh

  back:
    image: python:3.11-slim-buster
    restart: always
    working_dir: '/app'
    container_name: password_manager
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
        DATABASE_HOST: db
        ALLOWED_HOSTS: '127.0.0.1,localhost,0.0.0.0'
        DEBUG: 1
        DJANGO_SETTINGS_MODULE: "config.settings"
    command: bash -c "apt-get update
      && apt-get install -y curl
      && curl -sSl https://install.python-poetry.org | python3 -
      && export PATH=/root/.local/bin:$PATH
      && poetry install --no-root
      && poetry run python manage.py migrate
      && poetry run python manage.py runserver 0.0.0.0:8080"