#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER dev WITH SUPERUSER PASSWORD 'dev';
	CREATE DATABASE pm;
	ALTER DATABASE pm OWNER TO dev;
	GRANT ALL PRIVILEGES ON DATABASE pm TO dev;
EOSQL